name: chd_auth
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  device_info: ^2.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5
  device_info_plus: ^10.1.0

flutter:
  uses-material-design: true
